server:
  port: 0
  servlet:
    context-path: /userservice
---

springdoc:
  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: AnisMohamadi5651$


  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

---
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 15MB

---

spring:
  application:
    name: user-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true